logger: 
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

base_dir: "platform_processor_catalog/gold/gold_csv"

tables:
  combined_databases: "combined_databases"
  combined_users: "combined_users"
  company: "company"
  customer_addon_details: "customer_addon_details"
  customer_edition_details: "customer_edition_details"
  edition_function_details: "edition_function_details"
  license_customer_product: "license_customer_product"
  mavim_databases_details: "mavim_databases_details"
  mpm_customers: "mpm_customers"
  portal_monthly_users_report: "portal_monthly_users_report"
  portal: "portal"
  users: "users"
  company_global_admins: "company_global_admins"
